var havamal = [
"The man who stands at a strange threshold, Should be cautious before he cross it, Glance this way and that: Who knows beforehand what foes may sit Awaiting him in the hall?",
"Greetings to the host, The guest has arrived, In which seat shall he sit? Rash is he who at unknown doors Relies on his good luck,",
"Fire is needed by the newcomer Whose knees are frozen numb; Meat and clean linen a man needs Who has fared across the fells,",
"Water, too, that he may wash before eating, Handcloth's and a hearty welcome, Courteous words, then courteous silence That he may tell his tale,",
"Who travels widely needs his wits about him, The stupid should stay at home: The ignorant man is often laughed at When he sits at meat with the sage,",
"Of his knowledge a man should never boast, Rather be sparing of speech When to his house a wiser comes: Seldom do those who are silent Make mistakes; mother wit Is ever a faithful friend,",
"A guest should be courteous When he comes to the table And sit in wary silence, His ears attentive, his eyes alert: So he protects himself,",
"Fortunate is he who is favored in his lifetime With praise and words of wisdom: Evil counsel is often given By those of evil heart,",
"Blessed is he who in his own lifetime Is awarded praise and wit, For ill counsel is often given By mortal men to each other,",
"Better gear than good sense A traveler cannot carry, Better than riches for a wretched man, Far from his own home,",
"Better gear than good sense A traveler cannot carry, A more tedious burden than too much drink A traveler cannot carry,",
"Less good than belief would have it Is mead for the sons of men: A man knows less the more he drinks, Becomes a befuddled fool,",
"I forget is the name men give the heron Who hovers over the feast: Fettered I was in his feathers that night, When a guest in Gunnlod's court",
"Drunk I got, dead drunk, When Fjalar the wise was with me: Best is the banquet one looks back on after, And remembers all that happened,",
"Silence becomes the Son of a prince, To be silent but brave in battle: It befits a man to be merry and glad Until the day of his death,",
"The coward believes he will live forever If he holds back in the battle, But in old age he shall have no peace Though spears have spared his limbs",
"When he meets friends, the fool gapes, Is shy and sheepish at first, Then he sips his mead and immediately All know what an oaf he is,",
"He who has seen and suffered much, And knows the ways of the world, Who has traveled', can tell what spirit Governs the men he meets,",
"Drink your mead, but in moderation, Talk sense or be silent: No man is called discourteous who goes To bed at an early hour",
"A gluttonous man who guzzles away Brings sorrow on himself: At the table of the wise he is taunted often, Mocked for his bloated belly,",
"The herd knows its homing time, And leaves the grazing ground: But the glutton never knows how much His belly is able to hold,",
"An ill tempered, unhappy man Ridicules all he hears, Makes fun of others, refusing always To see the faults in himself",
"Foolish is he who frets at night, And lies awake to worry' A weary man when morning comes, He finds all as bad as before,",
"The fool thinks that those who laugh At him are all his friends, Unaware when he sits with wiser men How ill they speak of him.",
"The fool thinks that those who laugh At him are all his friends: When he comes to the Thing and calls for support, Few spokesmen he finds",
"The fool who fancies he is full of wisdom While he sits by his hearth at home. Quickly finds when questioned by others . That he knows nothing at all.",
"The ignorant booby had best be silent When he moves among other men, No one will know what a nit-wit he is Until he begins to talk; No one knows less what a nit-wit he is Than the man who talks too much.",
"To ask well, to answer rightly, Are the marks of a wise man: Men must speak of men's deeds, What happens may not be hidden.",
"Wise is he not who is never silent, Mouthing meaningless words: A glib tongue that goes on chattering Sings to its own harm.",
"A man among friends should not mock another: Many believe the man Who is not questioned to know much And so he escapes their scorn.",
"The wise guest has his way of dealing With those who taunt him at table: He smiles through the meal, not seeming to hear The twaddle talked by his foes",
"The fastest friends may fall out When they sit at the banquet-board: It is, and shall be, a shameful thing When guest quarrels with guest,",
"An early meal a man should take Before he visits friends, Lest, when he gets there, he go hungry, Afraid to ask for food.",
"To a false friend the footpath winds Though his house be on the highway. To a sure friend there is a short cut, Though he live a long way off.",
"The tactful guest will take his leave Early, not linger long: He starts to stink who outstays his welcome In a hall that is not his own.",
"A small hut of one's own is better, A man is his master at home: A couple of goats and a corded roof Still are better than begging.",
"A small hut of one's own is better, A man is his master at home: His heart bleeds in the beggar who must Ask at each meal for meat.",
"A wayfarer should not walk unarmed, But have his weapons to hand: He knows not when he may need a spear, Or what menace meet on the road.",
"No man is so generous he will jib at accepting A gift in return for a gift, No man so rich that it really gives him Pain to be repaid.",
"Once he has won wealth enough, A man should not crave for more: What he saves for friends, foes may take; Hopes are often liars.",
"With presents friends should please each other, With a shield or a costly coat: Mutual giving makes for friendship So long as life goes well,",
"A man should be loyal through life to friends, And return gift for gift, Laugh when they laugh, but with lies repay A false foe who lies.",
"A man should be loyal through life to friends, To them and to friends of theirs, But never shall a man make offer Of friendship to his foes.",
"If you find a friend you fully trust And wish for his good-will, exchange thoughts, exchange gifts, Go often to his house.",
"If you deal with another you don't trust But wish for his good-will, Be fair in speech but false in thought And give him lie for lie.",
"Even with one you ill-trust And doubt what he means to do, False words with fair smiles May get you the gift you desire.",
"Young and alone on a long road, Once I lost my way: Rich I felt when I found a another; Man rejoices in man.",
"The generous and bold have the best lives, Are seldom beset by cares, But the base man sees bogies everywhere And the miser pines for presents.",
"Two wooden stakes stood on the plain, on them I hung my clothes: Draped in linen, they looked well born, But, naked, I was a nobody",
"The young fir that falls and rots Having neither needles nor bark, So is the fate of the friendless man: Why should he live long?",
"Hotter than fire among false hearts burns Friendship for five days, But suddenly slackens when the sixth dawns: Feeble their friendship then.",
"A kind word need not cost much, The price of praise can be cheap: With half a loaf and an empty cup I found myself a friend,",
"Little a sand-grain, little a dew drop, Little the minds of men: All men are not equal in wisdom, The half-wise are everywhere",
"It is best for man to be middle-wise, Not over cunning and clever: The learned man whose lore is deep Is seldom happy at heart.",
"It is best for man to be middle-wise, Not over cunning and clever: The fairest life is led by those Who are deft at all they do.",
"It is best for man to be middle-wise, Not over cunning and clever: No man is able to know his future, So let him sleep in peace.",
"Brand Kindles Till they broun out, Flame is quickened by flame: One man from another is known by his speech The simpleton by his silence.",
"Early shall he rise who has designs On anothers land or life: His prey escapes the prone wolf, The sleeper is seldom victorious.",
"Early shall he rise who rules few servants, And set to work at once: Much is lost by the late sleeper, Wealth is won by the swift,",
"A man should know how many logs And strips of bark from the birch To stock in autumn, that he may have enough Wood for his winter fires.",
"Washed and fed, one may fare to the Thing: Though one's clothes be the worse for Wear, None need be ashamed of his shoes or hose, Nor of the horse he owns, Although no thoroughbred.",
"As the eagle who comes to the ocean shore, Sniffs and hangs her head, Dumfounded is he who finds at the Thing No supporters to plead his case.",
"It is safe to tell a secret to one, Risky to tell it to two, To tell it to three is thoughtless folly, Everyone else will know.",
"Moderate at council should a man be, Not brutal and over bearing: Among the bold the bully will find Others as bold as he.",
"Often words uttered to another Have reaped an ill harvest:",
"Too early to many homes I came, Too late, it seemed, to some; The ale was finished or else un-brewed, The unpopular cannot please.",
"Some would invite me to visit their homes, But none thought I Had eaten a whole joint, Just before with a friend who had two.",
"These things are thought the best: Fire, the sight of the sun, Good health with the gift to keep it, And a life that avoids vice.",
"Not all sick men are utterly wretched: Some are blessed with sons, Some with friends, some with riches, Some with worthy works.",
"It is always better to be alive, The living can keep a cow. Fire, I saw, warming a wealthy man, With a cold corpse at his door.",
"The halt can manage a horse, the handless a flock, The deaf be a doughty fighter, To be blind is better than to burn on a pyre: There is nothing the dead can do.",
"A son is a blessing, though born late To a father no longer alive: Stones would seldom stand by the highway If sons did not set them there.",
"Two beat one, the tongue is head's bane, Pockets of fur hide fists.",
"He welcomes the night who has enough provisions Short are the sails of a ship, Dangerous the dark in autumn, The wind may veer within five days, And many times in a month.",
"The half wit does not know that gold Makes apes of many men: One is rich, one is poor There is no blame in that.",
"Cattle die, kindred die, Every man is mortal: But the good name never dies Of one who has done well",
"Cattle die, kindred die, Every man is mortal: But I know one thing that never dies, The glory of the great dead",
"Fields and flocks had Fitjung's sons, Who now carry begging bowls: Wealth may vanish in the wink of an eye, Gold is the falsest of friends.",
"In the fool who acquires cattle and lands, Or wins a woman's love, His wisdom wanes with his waxing pride, He sinks from sense to conceit.",
"Now is answered what you ask of the runes, Graven by the gods, Made by the All Father, Sent by the powerful sage: lt. is best for man to remain silent.",
"For these things give thanks at nightfall: The day gone, a guttered torch, A sword tested, the troth of a maid, Ice crossed, ale drunk.",
"Hew wood in wind-time, in fine weather sail, Tell in the night-time tales to house-girls, For too many eyes are open by day: From a ship expect speed, from a shield, cover, Keenness from a sword, but a kiss from a girl.",
"Drink ale by the hearth, over ice glide, Buy a stained sword, buy a starving mare To fatten at home: and fatten the watch-dog.",
"No man should trust a maiden's words, Nor what a woman speaks: Spun on a wheel were women's hearts, In their breasts was implanted caprice,",
"A snapping bow, a burning flame, A grinning wolf, a grunting boar, A raucous crow, a rootless tree, A breaking wave, a boiling kettle,",
"A flying arrow, an ebbing tide, A coiled adder, the ice of a night, A bride's bed talk, a broad sword, A bear's play, a prince' s children,",
"A witch' s welcome, the wit of a slave, A sick calf, a corpse still fresh,",
"A brother's killer encountered upon The highway a house half-burned, A racing stallion who has wrenched a leg, Are never safe: let no man trust them.",
"Trust not an acre early sown, Nor praise a son too soon: Weather rules the acre, wit the son, Both are exposed to peril,",
"To love a woman whose ways are false Is like sledding over slippery ice With unshod horses out of control, Badly trained two-year-olds, Or drifting rudderless on a rough sea, Or catching a reindeer with a crippled hand On a thawing hillside: think not to do it.",
"Naked I may speak now for I know both: Men are treacherous too Fairest we speak when falsest we think: many a maid is deceived.",
"Gallantly shall he speak and gifts bring Who wishes for woman's love: praise the features of the fair girl, Who courts well will conquer.",
"Never reproach another for his love: It happens often enough That beauty ensnares with desire the wise While the foolish remain unmoved.",
"Never reproach the plight of another, For it happens to many men: Strong desire may stupefy heroes, Dull the wits of the wise",
"The mind alone knows what is near the heart, Each is his own judge: The worst sickness for a wise man Is to crave what he cannot enjoy.",
"So I learned when I sat in the reeds, Hoping to have my desire: Lovely was the flesh of that fair girl, But nothing I hoped for happened.",
"I saw on a bed Billing's daughter, Sun white, asleep: No greater delight I longed for then Than to lie in her lovely arms.",
"Come Odhinn, after nightfall If you wish for a meeting with me: All would be lost if anyone saw us And learned that we were lovers.",
"Afire with longing; I left her then, Deceived by her soft words: I thought my wooing had won the maid, That I would have my way.",
"After nightfall I hurried back, But the warriors were all awake, Lights were burning, blazing torches: So false proved the path",
"Towards daybreak back I came The guards were sound asleep: I found then that the fair woman Had tied a bitch to her bed.",
"Many a girl when one gets to know her Proves to be fickle and false: That treacherous maiden taught me a lesson, The crafty woman covered me with shame That was all I got from her.",
"Let a man with his guests be glad and merry, Modest a man should be; But talk well if he intends to be wise And expects praise from men: Fimbul fambi is the fool called; Unable to open his mouth.",
"Fruitless my errand, had I been silent When I came to Suttung's courts: With spirited words I spoke to my profit In the hall of the aged giant.",
"Rati had gnawed a narrow passage, Chewed a channel through stone, A path around the roads of giants: I was like to lose my head",
"Gunnlod sat me in the golden seat, Poured me precious mead: Ill reward she had from me for that, For her proud and passionate heart, Her brooding foreboding spirit. 107 What I won from her I have well used: I have waxed in wisdom since I came back, bringing to Asgard Odrerir, the sacred draught.",
"Hardly would I have come home alive From the garth of the grim troll, Had Gunnlod not helped me, the good woman, Who wrapped her arms around me.",
"The following day the Frost Giants came, Walked into Har's hall To ask for Har's advice: Had Bolverk they asked, come back to his friends, Or had he been slain by Suttung?",
"Odhinn, they said, swore an oath on his ring: Who from now on will trust him? By fraud at the feast he befuddled Suttung And brought grief to Gunnlod.",
"It is time to sing in the seat of the wise, Of what at Urd's Well I saw in silence, saw and thought on. Long I listened to men Runes heard spoken, (counsels revealed.) At Har's hall, In Har's hall: There I heard this.",
"Loddfafnir, listen to my counsel: You will fare well if you follow it, It will help you much if you heed it. Never rise at night unless you need to spy Or to ease yourself in the outhouse.",
"Shun a woman, wise in magic, Her bed and her embraces:",
"If she cast a spell, you will care no longer To meet and speak with men, Desire no food, desire no pleasure, In sorrow fall asleep.",
"Never seduce anothers wife, Never make her your mistress.",
"If you must journey to mountains and firths, Take food and fodder with you.",
"Never open your heart to an evil man When fortune does not favour you: From an evil man, if you make him your friend, You will get evil for good.",
"I saw a warrior wounded fatally By the words of an evil woman Her cunning tongue caused his death, Though what she alleged was a lie.",
"If you know a friend you can fully trust, Go often to his house Grass and brambles grow quickly Upon the untrodden track.",
"With a good man it is good to talk, Make him your fast friend: But waste no words on a witless oaf, Nor sit with a senseless ape.",
"Cherish those near you, never be The first to break with a friend: Care eats him who can no longer Open his heart to another.",
"An evil man, if you make him your friend, Will give you evil for good:",
"A good man, if you make him your friend; Will praise you in every place,",
"Affection is mutual when men can open All their heart to each other: He whose words are always fair Is untrue and not to be trusted.",
"Bandy no speech with a bad man: Often the better is beaten In a word fight by the worse.",
"Be not a cobbler nor a carver of shafts, Except it be for yourself: If a shoe fit ill or a shaft be crooked; The maker gets curses and kicks.",
"If aware that another is wicked, say so: Make no truce or treaty with foes.",
"Never share in the shamefully gotten, But allow yourself what is lawful.",
"Never lift your eyes and look up in battle, Lest the heroes enchant you, who can change warriors Suddenly into hogs,",
"With a good woman, if you wish to enjoy Her words and her good will, Pledge her fairly and be faithful to it: Enjoy the good you are given,",
"Be not over wary, but wary enough, First, of the foaming ale, Second, of a woman wed to another, Third, of the tricks of thieves.",
"Mock not the traveler met On the road, Nor maliciously laugh at the guest:",
"The sitters in the hall seldom know The kin of the new-comer: The best man is marred by faults, The worst is not without worth.",
"Never laugh at the old when they offer counsel, Often their words are wise: From shriveled skin, from scraggy things",
"That hand among the hides And move amid the guts, Clear words often come.",
"135 Scoff not at guests nor to the gate chase them, But relieve the lonely and wretched,",
"Heavy the beam above the door; Hang a horse-shoe On it Against ill-luck, lest it should suddenly Crash and crush your guests.",
"Medicines exist against many evils: Earth against drunkenness, heather against worms Oak against costiveness, corn against sorcery, Spurred rye against rupture, runes against bales The moon against feuds, fire against sickness, Earth makes harmless the floods.",
"138 Wounded I hung on a wind-swept gallows For nine long nights, Pierced by a spear, pledged to Odhinn, Offered, myself to myself The wisest know not from whence spring The roots of that ancient rood",
"They gave me no bread, They gave me no mead, I looked down; with a loud cry I took up runes; from that tree I fell.",
"Nine lays of power I learned from the famous Bolthor, Bestla' s father: He poured me a draught of precious mead, Mixed with magic Odrerir.",
"Waxed and throve well; Word from word gave words to me, Deed from deed gave deeds to me,",
"Runes you will find, and readable staves, Very strong staves, Very stout staves, Staves that Bolthor stained, Made by mighty powers, Graven by the prophetic god,",
"For the gods by Odhinn, for the elves by Dain, By Dvalin, too, for the dwarves, By Asvid for the hateful giants, And some I carved myself: Thund, before man was made, scratched them, Who rose first, fell thereafter",
"Know how to cut them, know how to read them, Know how to stain them, know how to prove them, Know how to evoke them, know how to score them, Know how to send them; know how to send them,",
"Better not to ask than to over-pledge As a gift that demands a gift; Better not to send than to slay too many,",
"The first charm I know is unknown to rulers Or any of human kind; Help it is named, for help it can give In hours of sorrow and anguish.",
"I know a second that the sons of men Must learn who wish to be leeches.",
"I know a third: in the thick of battle, If my need be great enough, It will blunt the edges of enemy swords, Their weapons will make no wounds.",
"I know a fourth: it will free me quickly If foes should bind me fast With strong chains, a chant that makes Fetters spring from the feet, Bonds burst from the hands.",
"I know a fifth: no flying arrow, Aimed to bring harm to men, Flies too fast for my fingers to catch it And hold it in mid-air.",
"I know a sixth: it will save me if a man Cut runes on a sapling' s Roots With intent to harm; it turns the spell; The hater is harmed, not me.",
"I know a seventh: If I see the hall Ablaze around my bench mates, Though hot the flames, they shall feel nothing, If I choose to chant the spell.",
"I know an eighth: that all are glad of, Most useful to men: If hate fester in the heart of a warrior, It will soon calm and cure him.",
"I know a ninth: when need I have To shelter my ship on the flood, The wind it calms, the waves it smoothes And puts the sea to sleep,",
"I know a tenth: if troublesome ghosts Ride the rafters aloft, I can work it so they wander astray, Unable to find their forms, Unable to find their homes.",
"I know an eleventh: when I lead to battle Old comrades in-arms, I have only to chant it behind my shield, And unwounded they go to war, Unwounded they come from war, Unscathed wherever they are.",
"I know a twelfth: If a tree bear A man hanged in a halter, I can carve and stain strong runes That will cause the corpse to speak, Reply to whatever I ask.",
"I know a thirteenth if I throw a cup Of water over a warrior, He shall not fall in the fiercest battle, Nor sink beneath the sword,",
"I know a fourteenth, that few know: If I tell a troop of warriors About the high ones, elves and gods, I can name them one by one. (Few can the nit-wit name.)",
"I know a fifteenth, that first Thjodrerir Sang before Delling's doors, Giving power to gods, prowess to elves, Fore-sight to Hroptatyr Odhinn,",
"I know a sixteenth: if I see a girl With whom it would please me to play, I can turn her thoughts, can touch the heart Of any white armed woman.",
"I know a seventeenth: if I sing it, the young Girl will be slow to forsake me.",
"To learn to sing them, Loddfafnir, Will take you a long time, Though helpful they are if you understand them, Useful if you use them, Needful if you need them.",
"I know an eighteenth that I never tell To maiden or wife of man, A secret I hide from all Except the love who lies in my arms, Or else my own sister.",
"The Wise One has spoken words in the hall, Needful for men to know, Unneedful for trolls to know: Hail to the speaker, Hail to the knower, Joy to him who has understood, Delight to those who have listened."
];

randomHavamal = function(){
  var min = 0;
  var max = havamal.length;
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

displayHavamal = function(currentHavamal){
  document.write(havamal[currentHavamal]);
  document.write("<br>Havamal " + currentHavamal);
}
